# Generated by Django 5.2.15 on 2026-06-13 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('geocode_source', models.CharField(blank=True, max_length=32, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['geocode_status'], name='fuel_fuelst_geocode_4ae95b_idx'), models.Index(fields=['state'], name='fuel_fuelst_state_641286_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_fuelst_latitud_e7de73_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('address_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('address_normalized', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('formatted_address', models.TextField()),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['address_normalized'], name='fuel_geocod_address_5e633d_idx')],
            },
        ),
    ]
